config/routes.rb
Rails.application.routes.draw do

 

  get 'users/update'

devise_for :users
resources :users, only: [:update, :show, :index]
  resources :questions
  
  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts'
  end
  
  resources :posts, only: [:index] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end
  
  
  
  resources :advertisements
  
  

  
  get 'about' => 'welcome#about'

  root to: 'welcome#index'
  

end

app/models/question.rb
class Question < ActiveRecord::Base
    has_many :answers
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end
  
  def create
      @question = Question.new(question_params)
      
      if @question.save
          redirect_to @question, notice: "Your question was saved"
      else
          flash[:error] = "Your quesiton failed to create."
          redirect_to questions_path
      end
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end
  
  def update
      @question = Question.find(params[:id])
      
      if @question.update_attributes(question_params)
          redirect_to @question, notice: "Question updated succesfully"
      else
          flash[:error] = "Something went wrong"
          render :edit
      end
  end
  
  def resolved 
    @question = Question.resolved
  end
  
  private
  
  def question_params
      params.require(:question).permit(:title, :body, :resolved)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit.html.erb
<%= form_for @question do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :body %>
    <%= f.text_area :body %>
    <%= f.check_box :resolved %>
    <%= f.submit %>
<% end %>

app/views/questions/index.html.erb
<% @questions.each do |question| %>
    <%= link_to question.title, question %>
<% end %>

app/views/questions/new.html.erb
<%= form_for @question do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :body %>
    <%= f.text_area :body %>
    <%= f.submit %>
<% end %>

app/views/questions/show.html.erb
<%= @question.title %>
<%= @question.body %>
<%= @question.resolved %>
<%= link_to "Edit", edit_question_path(@question), class: "btn btn-success" %>