config/routes.rb
Rails.application.routes.draw do

 

  get 'users/update'

devise_for :users
resources :users, only: [:update, :show, :index]
  resources :questions
  
  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts'
  end
  
  resources :posts, only: [:index] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end
  
  
  
  resources :advertisements
  
  

  
  get 'about' => 'welcome#about'

  root to: 'welcome#index'
  

end

app/models/topic.rb
class Topic < ActiveRecord::Base
    has_many :posts, dependent: :destroy
    
    
    scope :visible_to, -> (user) {user ? all : :publicly_viewable}
  
    Topic.order('created_at DESC')
    
    WillPaginate.per_page = 100
    
    validates :name, length: { minimum: 5 }, presence: true
    
    def publicly_viewable(user)
    if user
      topic_collection.all
    else
      topic_collection.where(public: true)
    end
    end

    def privately_viewable
     topic_collection.where(public: false)
    end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  has_many :posts
  has_many :comments
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  mount_uploader :avatar, AvatarUploader
  
  def favorited(post)
    favorites.where(post_id: post.id).first
  end
  
  def admin?
    role == 'admin'
  end
  
  def voted(post)
     votes.where(post_id: post.id).first
  end

  def moderator?
    role == 'moderator'
  end
  
  def self.top_rated
     self.select('users.*') # Select all attributes of the user
         .select('COUNT(DISTINCT comments.id) AS comments_count') # Count the comments made by the user
         .select('COUNT(DISTINCT posts.id) AS posts_count') # Count the posts made by the user
         .select('COUNT(DISTINCT comments.id) + COUNT(DISTINCT posts.id) AS rank') # Add the comment count to the post count and label the sum as "rank"
         .joins(:posts) # Ties the posts table to the users table, via the user_id
         .joins(:comments) # Ties the comments table to the users table, via the user_id
         .group('users.id') # Instructs the database to group the results so that each user will be returned in a distinct row
         .order('rank DESC') # Instructs the database to order the results in descending order, by the rank that we created in this query. (rank = comment count + post count)
  end
  
end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController
  
  
    
      
  def index
    @posts = Post.all
    authorize @posts
  end

  def show
    @post = Post.find(params[:id])
    @topic = Topic.find(params[:topic_id])
    authorize @post
    @comments = @post.comments
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize @post
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
  end
  
  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
    if @post.update_attributes(params.require(:post).permit(:title, :body))
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end
  
  def create
    @topic = Topic.find(params[:topic_id])
    @post = Post.new(post_params)
    @post.user = current_user
    @post.topic = @topic
    authorize @post
    #raise # this will short-circuit the method
    if @post.save_with_initial_vote
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
    
    def destroy
      @topic = Topic.find(params[:topic_id])
      @post = Post.find(params[:id])
      authorize @post
      
      if @post.destroy
        flash[:notice] = "\"#{@post.title}\" was deleted successfully."
        redirect_to @topic
      else
        flash[:error] = "There was an error deleting the post."
        render :show
      end
    end
  end
  
class PostsController < ApplicationController
   def index
     @posts = Post.visible_to(current_user).where("posts.created_at > ?", 7.days.ago).paginate(page: params[:page], per_page: 10)
   end
end
  
  private
  
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  
  def destroy
    @topic = Topic.find(params[:id])
    authorize @topic
    if @topic.destroy
      flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
      redirect_to topics_path
    else 
      flash[:error] = "There was an error deleting the topic."
      render :show
    end
  end
   
  def new
    @topic = Topic.new
    authorize @topic
  end
  
  def index
    @topics = Topic.visible_to(current_user).paginate(page: params[:page], per_page: 10)
    authorize @topics 
  end
  
  def edit 
    @topic = Topic.find(params[:id])
    authorize @topic
  end
  
  def show
    @topic = Topic.find(params[:id])
    @posts = @topic.posts.includes(:user).includes(:comments).paginate(page: params[:page], per_page: 10)
    authorize @topic
  end
  
  def create
    @topic = Topic.new(topic_params)
    authorize @topic
    if @topic.save
      redirect_to @topic, notice: "Topic was saved successfully."
    else
      flash[:error] = "Error creating topic. Please try again."
      render :new
    end 
  end
    

  
  def update
    @topic = Topic.find(topic_params)
    authorize @topic
    if @topic.update_attributes(params.require(:topic).permit(:name, :description, :public))
      redirect_to @topic
    else
      flash[:error] = "Error saving topic. Please try again."
      render :edit
    end
  end
  
  private
  
  def topic_params
    params.require(:topic).permit(:name, :description, :public)
  
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!, except: [:show]
 
  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated"
      redirect_to edit_user_registration_path
    else
      flash[:error] = "Invalid user information"
      redirect_to edit_user_registration_path
    end
  end
  
  def index
     @users = User.top_rated.paginate(page: params[:page], per_page: 10)
  end
  
  def show
     @user = User.find(params[:id])
     @posts = @user.posts.visible_to(current_user)
     @comments = @user.comments
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :avatar,:email_favorites)
  end
  
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/topics/_form.html.erb
		<%= form_for @topic do |f| %>
		<div class="form-group">
			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
	</div>
	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
	</div>
	<div class="form-group">
		<%= f.label :public, class: 'checkbox' do %>
		 <%= f.check_box :public %> Public topic
		<% end %>
	</div>
	<%= f.submit "Save", class: 'btn btn-success' %>
		<% end %>
		

app/views/users/topics/edit.html.erb
<h1>Edit Topic</h1>


<div class="row">
	<div class="col-md-4">
		<p>Guidelines for topics:</p>
		<ul>
			<li>Make sure the topic is appropriate.</li>
			<li>Never insult dogs.</li>
			<li>Smile when you type.</li>
		</ul>
	</div>
	<div class="col-md-8">

		<%= render partial: 'form', locals: { topic: @topic, post: @post } %>
		
	</div>
</div>
			

app/views/users/topics/index.html.erb
  <h1>Topics</h1>
  
  <div class="row">
    <div class="col-md-8">
      <% @topics.each do |topic| %>
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">
              <%= link_to topic.name, topic %>
            </h4>
            <small>
              <%= topic.description %>
            </small>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <% if policy(Topic.new).create? %>
        <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>

app/views/users/topics/show.html.erb
<h1><%= @topic.name %></h1>



<% @post_images.each do |p| %>
		<%= image_tag p.avatar_url %>
		<%= link_to "Edit Image", edit_post_image_path(p) %>
	<% end %>

<% if policy(@topic).update? %>
		<%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
<% end %>

<div class="row">
	<div class="col-md-8">
		<p class="lead"><%= @topic.description %></p>
		<% @posts.each do |post| %>
			<div class="media">
				<div class="media-body">
					<h4 class="media-heading">
						<%= link_to (markdown_to_html post.title), [@topic, post] %>
					</h4>
					<small>
						submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %><br>
						<%= post.comments.count %> Comments
					</small>
				</div>
			</div>
		<% end %>
	</div>
	<div class="col-md-4">
		<% if policy(Post.new).create? %>
		
		<%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
		<% end %>
	</div>
</div>