config/routes.rb
Rails.application.routes.draw do

 

  get 'users/update'

devise_for :users
resources :users, only: [:update, :show, :index]
  resources :questions
  
  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts'
  end
  
  resources :posts, only: [:index] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end
  
  
  
  resources :advertisements
  
  

  
  get 'about' => 'welcome#about'

  root to: 'welcome#index'
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :summaries
  belongs_to :user
  belongs_to :topic
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true
  #after_create :create_vote
  
  default_scope { order('rank DESC') }
  scope :visible_to, ->  { user ? all : joins(:topic).where('topics.public' => true) }
  scope :ordered_by_title, -> { update(ordered_by_title: true) }
  scope :ordered_by_reverse_created_at, -> { update(ordered_by_reverse_created_at: true)}
	
	def up_votes
	  votes.where(value: 1).count
	end
	
	def down_votes
	  votes.where(value: -1).count
	end
  
  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / (60 * 60 * 24) # 1 day in seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end

  def points
    votes.sum(:value).to_i
  end

  def markdown_title
  	render_as_markdown(self.title)
  end
  
  def markdown_body
  	render_as_markdown(self.body)
  end

  #private 

  def render_as_markdown(markdown)
      renderer = Redcarpet::Render::HTML.new
      extensions = {fenced_code_blocks: true}
      redcarpet = Redcarpet::Markdown.new(renderer, extensions)
      (redcarpet.render markdown).html_safe
  end
  

  def create_vote
    self.user.votes.create(value: 1, post: self)
  end
  def save_with_initial_vote
    ActiveRecord::Base.transaction do
      @post = self
      user.votes.create(value: 1, post: @post)
    end
  end
end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController
  
  
    
      
  def index
    @posts = Post.all
    authorize @posts
  end

  def show
    @post = Post.find(params[:id])
    @topic = Topic.find(params[:topic_id])
    authorize @post
    @comments = @post.comments
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize @post
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
  end
  
  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
    if @post.update_attributes(params.require(:post).permit(:title, :body))
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end
  
  def create
    @topic = Topic.find(params[:topic_id])
    @post = Post.new(post_params)
    @post.user = current_user
    @post.topic = @topic
    authorize @post
    #raise # this will short-circuit the method
    if @post.save_with_initial_vote
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
    
    def destroy
      @topic = Topic.find(params[:topic_id])
      @post = Post.find(params[:id])
      authorize @post
      
      if @post.destroy
        flash[:notice] = "\"#{@post.title}\" was deleted successfully."
        redirect_to @topic
      else
        flash[:error] = "There was an error deleting the post."
        render :show
      end
    end
  end
  
class PostsController < ApplicationController
   def index
     @posts = Post.visible_to(current_user).where("posts.created_at > ?", 7.days.ago).paginate(page: params[:page], per_page: 10)
   end
end
  
  private
  
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>

	
	<%= f.fields_for :post_images do |p| %>
	<div class="field">
		<%= p.label :avatar %><br>
		<%= p.file_field :avatar, :multiple => true, name: "post_images[avatar][]" %>
	</div>
	<% end %>
	<div class="actions">
		<%= f.submit %>
	</div>


  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
        	<li><%= msg %></li>
  			<% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(post.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
  <% end %>
  <%= form_group_tag(post.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>
  

app/views/posts/_post.html.erb
<div class="media">
  <%# render partial: 'votes/voter', locals: { post: post } %>
    <div class="media-body">
      <h4 class="media-heading">
          <%# image_tag(post.image.thumb.url) if post.image? %>
          <%= link_to post.title, [post.topic, post] %>
      </h4>
        <small>
          <%= image_tag(post.user.avatar.tiny.url) if post.user.avatar? %>
          submitted <%= time_ago_in_words(post.created_at) %> ago by
          <%= post.user.name %><br>
          <%= post.comments.count %> Comments
        </small>
      </div>
         
</div>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<% if policy(Post.new).create? %>
<%= link_to "New Post", new_post_path, class: 'btn btn-success' %>
<% end %>

<% @posts.each do |post| %>
<div class="media">
	<div class="media-body">
		<h4 class="media-heading">
			<%= link_to post.title, post %>
		</h4>
			<small>
				submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %><br>
				<%= post.comments.count %> Comments
			</small>
		</div>
	</div>
	
<% end %>

<div class="row">
   <div class="col-md-8">
     <h1>Popular</h1>
     <p class="lead">Active posts this week</p>
     <%= render @posts %>
     <%= will_paginate @posts %>
   </div>
   <div class="col-md-4">
   </div>
 </div>

app/views/posts/show.html.erb
<h1><%= @post.markdown_title %></h1>

<div class="row">
	<div class="col-md-8">
		<%= render partial: 'votes/voter', locals: { post: @post } %>
		<p><%= @post.markdown_body %></p>
	</div>
	
	
	<div class="col-md-4">
		<% if policy(@post).edit? %>
		<%= link_to "Edit", edit_topic_post_path(@topic, @post), class: 'btn btn-success' %>
		<% end %>
	</div>
		
		<% if policy(@post).destroy? %>
		<%= link_to "Delete Post", [@topic, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' } %>
		<% end %>
		
		<div>
			<h3><%= pluralize(@post.points, 'point') %></h3>
			<small>
				<%= pluralize(@post.up_votes, 'up vote') %>,
				<%= pluralize(@post.down_votes, 'down vote') %>
				</small>
		</div>
		<%= render partial: 'favorites/favorite', locals: { post: @post } %>
	</div>
</div>
</br>

<div class="row">
	<h2>Comments</h2>
	<div class='col-md-12'>
		<%= render @comments %>
		<%= render partial: 'comments/form', locals: {topic: @topic, post: @post} %>
	</div>
</div>